// C driver for Arm64 code generated by Arm64.fs and Arm64Comp.fs and
// clang's assembler, for Linux and MacOS.  Defines the initial
// entrypoint (main) which calls the assembly entrypoint (asm_main),
// and utility functions (printc, printf, checkargc) called from the
// assembly code.

// In MacOS assembly, but not in this file nor in Linux assembly,
// global names must be prefixed by an underscore: _asm_main, _printc,
// _printi and _checkargc.

// sestoft@itu.dk * 2025-11-25 based on Kokholm's 2002 x86 version 


#include <stdio.h>
#include <stdlib.h>
#include <time.h>

extern void asm_main(long,long*);

long printc(long c) { printf("%c", (int)c); return c; }

long printi(long i) { printf("%ld ", i); return i; }

void checkargc(long given, long expected) { 
  if (given > 8) {
    printf("More than 8 command line arguments: %ld\n", given); 
    exit(1);
  }
  if (given != expected) {
    printf("Wrong argument count: expected %ld but got %ld\n", expected, given); 
    exit(1);
  }
}

int main(int argc, char **argv) {
  long args[63];
  for (int i=1; i<argc; i++) 
    args[i-1] = atol(argv[i]);
  asm_main(argc-1,args);
  printf("\nRan %.3f s\n",(clock())*1.0/CLOCKS_PER_SEC);
  exit(0);
}
